name: nextgen_forcings_engine
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - bmipy
  - bokeh
  - pandas
  - python
  - ruamel.yaml
  - netCDF4
  - mpi4py
  - scipy
  - dask
  - s3fs
  - xarray
  - zarr
  - esmpy
  - numpy

